'use strict';
/* Bilingual-Term-Extract —— 术语表导出
 * TBX (v02 martif，可导入 Trados MultiTerm / memoQ)、CSV（Excel 友好 BOM）、JSON、Markdown。
 * entries 结构：{ src, tgt, freq, conf, status, pos, domain, note }
 */
const { escapeXml, timestamp } = require('./util.js');

function toTBX(entries, srcLang, tgtLang, title) {
  const L = [];
  L.push('<?xml version="1.0" encoding="UTF-8"?>');
  L.push('<!DOCTYPE martif SYSTEM "TBXcoreStructV02.dtd">');
  L.push('<martif type="TBX" xml:lang="' + escapeXml(srcLang) + '">');
  L.push('<martifHeader>');
  L.push('<fileDesc>');
  L.push('<titleStmt><title>' + escapeXml(title || 'Bilingual-Term-Extract glossary') + '</title></titleStmt>');
  L.push('<sourceDesc><p>Generated by Bilingual-Term-Extract at ' + timestamp() + '</p></sourceDesc>');
  L.push('</fileDesc>');
  L.push('</martifHeader>');
  L.push('<text><body>');
  entries.forEach((e, i) => {
    L.push('<termEntry id="e' + (i + 1) + '">');
    if (e.domain) L.push('<descrip type="subjectField">' + escapeXml(e.domain) + '</descrip>');
    const notes = [];
    if (e.note) notes.push(e.note);
    if (e.status === 'review') notes.push('需人工复核');
    if (notes.length) L.push('<descrip type="usageNote">' + escapeXml(notes.join('；')) + '</descrip>');
    L.push('<langSet xml:lang="' + escapeXml(srcLang) + '"><tig>');
    L.push('<term>' + escapeXml(e.src) + '</term>');
    if (e.pos) L.push('<termNote type="partOfSpeech">' + escapeXml(e.pos) + '</termNote>');
    L.push('</tig></langSet>');
    L.push('<langSet xml:lang="' + escapeXml(tgtLang) + '"><tig>');
    L.push('<term>' + escapeXml(e.tgt) + '</term>');
    L.push('</tig></langSet>');
    L.push('</termEntry>');
  });
  L.push('</body></text>');
  L.push('</martif>');
  return L.join('\n');
}

function csvField(v) {
  const s = String(v == null ? '' : v);
  return '"' + s.replace(/"/g, '""') + '"';
}

function toCSV(entries) {
  const head = 'source_term,target_term,freq,confidence,status,pos,domain,note';
  const rows = entries.map(e => [e.src, e.tgt, e.freq, e.conf, e.status, e.pos || '', e.domain || '', e.note || ''].map(csvField).join(','));
  return '\uFEFF' + head + '\n' + rows.join('\n') + (rows.length ? '\n' : '');
}

function toJSON(entries, meta) {
  return JSON.stringify({ app: 'bilingual-term-extract', version: 1, meta: meta || {}, terms: entries }, null, 2) + '\n';
}

function toMD(entries, srcLang, tgtLang) {
  const L = [];
  L.push('| # | 源语术语 (' + srcLang + ') | 目标语术语 (' + tgtLang + ') | 置信度 | 频次 | 状态 | 词性 | 领域 | 备注 |');
  L.push('|---|---|---|---|---|---|---|---|---|');
  entries.forEach((e, i) => {
    const esc = s => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
    L.push('| ' + (i + 1) + ' | ' + esc(e.src) + ' | ' + esc(e.tgt) + ' | ' + (e.conf != null ? e.conf : '') +
      ' | ' + (e.freq != null ? e.freq : '') + ' | ' + esc(e.status) + ' | ' + esc(e.pos) + ' | ' + esc(e.domain) + ' | ' + esc(e.note) + ' |');
  });
  return L.join('\n') + '\n';
}

module.exports = { toTBX, toCSV, toJSON, toMD };
